# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media_cdn'),
        ),
    ]
